In [1]:
import torch

In [3]:
t1=torch.tensor(4)
t1.dtype

torch.int64

In [5]:
t2=torch.tensor(4.)
t2.dtype

torch.float32

In [9]:
t3=torch.tensor([[1,2],[3,4]])
t3.shape

torch.Size([2, 2])

In [12]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [69]:
x = torch.tensor(3.)
w = torch.tensor([4.], requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor([4.], requires_grad=True), tensor(5., requires_grad=True))

In [70]:
y=w*x+b
y

tensor([17.], grad_fn=<AddBackward0>)

In [71]:
#Calculating derivative
y.backward()

In [72]:
#dy/dx
print(x.grad)

#dy/dw
print(w.grad)

#dy/db
print(b.grad)

None
tensor([3.])
tensor(1.)


In [81]:
x = torch.tensor([3.,3.])
w = torch.tensor([4.,4.], requires_grad=True)
b = torch.tensor([5.,5.], requires_grad=True)
x, w, b

(tensor([3., 3.]),
 tensor([4., 4.], requires_grad=True),
 tensor([5., 5.], requires_grad=True))

In [82]:
y=w*w + b
y

tensor([21., 21.], grad_fn=<AddBackward0>)

In [85]:
x = torch.tensor(1.0, requires_grad = True)
y = torch.tensor(2.0)
z = x * y

# Displaying
for i, name in zip([x, y, z], "xyz"):
    print(f"{name}\ndata: {i.data}\nrequires_grad: {i.requires_grad}\n\
grad: {i.grad}\ngrad_fn: {i.grad_fn}\nis_leaf: {i.is_leaf}\n")

x
data: 1.0
requires_grad: True
grad: None
grad_fn: None
is_leaf: True

y
data: 2.0
requires_grad: False
grad: None
grad_fn: None
is_leaf: True

z
data: 2.0
requires_grad: True
grad: None
grad_fn: <MulBackward0 object at 0x127114f98>
is_leaf: False



# 

In [48]:
import numpy as np

In [53]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [52]:
t_from_np = torch.from_numpy(x)
t_from_np

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [58]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

np_from_t=t4.numpy()
np_from_t

array([[[11., 12., 13.],
        [13., 14., 15.]],

       [[15., 16., 17.],
        [17., 18., 19.]]], dtype=float32)

In [60]:
np_from_t.shape

(2, 2, 3)